### ISSUE TITLE
How to use the API

### ISSUE THREAD

**Issue by joe528** [stensoosaar/IBKit#1]
I am tryin to use IBKit. It looks great.

However, I don't even know how to initialize the API and start to use it. 

Is there any document or could you provide more details about how to init the API and how to request historical price for a stock, for example?

**Comment by stensoosaar** [comment]
I believe you will find a sample with comments in IBPlayground>MarketData. Of course, as a very first thing, you must download and run tws gateway available here: https://www.interactivebrokers.com/en/trading/ib-api.php. 

PS. The currently tested api version is 10.18, and there is an intention to update it in sync with Xcode major releases around September-October each year.

**Comment by joe528** [comment]
Ah.. I see. I overlooked, there are actually more files in the playground. Thanks. I will take a look.
